ENV['COCOAPODS_DISABLE_STATS'] = "true"

platform :ios, '11.0'

use_frameworks!

target 'Backit' do
    pod 'NewRelicAgent'
end

target 'BackitTests' do
#   pod 'AutoEquatable'
    pod 'KIF/IdentifierTests'
    pod 'Spry'
    pod 'Spry+Nimble'
end
