platform :ios, '11.0'

use_frameworks!

target 'Backit' do
    pod 'Alamofire'
    pod 'BrightFutures'
    pod 'Mixpanel'
    pod 'SDWebImage'
    pod 'Swinject'
    pod 'SwinjectStoryboard'
end

target 'BackitTests' do
    pod 'BrightFutures'
    pod 'Quick'
    pod 'Nimble'
    pod 'KIF'
    pod 'KIF-Quick'
    pod 'Spry'
    pod 'Spry+Nimble'
    pod 'AutoEquatable'
end
