ENV['COCOAPODS_DISABLE_STATS'] = "true"

platform :ios, '11.0'

use_frameworks!

target 'BackitTests' do
    pod 'AutoEquatable'
    pod 'KIF'
    pod 'KIF-Quick'
    pod 'Nimble'
    pod 'Quick'
    pod 'Spry'
    pod 'Spry+Nimble'
end
