name: Backit
options:
   minimumXcodeGenVersion: 2.6.0
   #  configFiles: Debug: configs/Debug.xcconfig
   #  Release: configs/Release.xcconfig
targets:
  Backit:
    platform: iOS
    type: application
    sources:
      - path: main.swift
      - path: Info.plist
      - path: Application
        excludes:
          - "Analytics/MixpanelAnalyticsListener.swift"
      - path: Domain
      - path: Service
      - path: UI
        #    configFiles:
        #        Debug: configs/BitriseClient-Debug.xcconfig
        #        Release: configs/BitriseClient-Release.xcconfig
        #    settings:
        #      FRAMEWORK_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/SDK/NewRelicAgent/ $(PROJECT_DIR)/SDK/google_signin_sdk_4_4_0/"
    dependencies:
      - sdk: CoreTelephony.framework
      - sdk: SystemConfiguration.framework
      - sdk: libc++.tbd
      - sdk: libz.tbd
      - framework: SDK/NewRelicAgent/NewRelicAgent.framework
      - carthage: Alamofire
      - carthage: BrightFutures
      - carthage: FacebookCore
      - carthage: FacebookLogin
      - carthage: FBSDKCoreKit
      - carthage: FBSDKLoginKit
      - carthage: FMDB
      - carthage: Hero
      - carthage: KeychainAccess
      - carthage: SDWebImage
      - carthage: Swinject
      - carthage: SwinjectStoryboard
      - target: BKFoundation
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.backit.ios.backer
        SWIFT_OBJC_BRIDGING_HEADER: Backit-Bridging-Header.h
    configs:
        Debug:
          CODE_SIGN_IDENTITY: "iPhone Developer"
    scheme:
      environmentVariables:
        ENABLE_SIGNPOST: YES
  BackitTests:
    platform: iOS
    type: bundle.unit-test
    #    configFiles:
    #    Debug: configs/BitriseClientTests-Debug.xcconfig
    sources:
      - BackitTests/
    dependencies:
      - target: Backit
    scheme:
      testTargets:
        - BackitTests
      gatherCoverageData: true
  BKFoundation:
    platform: iOS
    type: framework
    sources:
      - Foundation/
    dependencies:
      - carthage: BrightFutures
