name: Backit
options:
  minimumXcodeGenVersion: 2.6.0
targets:
  Backit:
    platform: iOS
    type: application
    sources:
      - path: main.swift
      - path: Info.plist
      - path: Application
        excludes:
          - "Analytics/MixpanelAnalyticsListener.swift"
      - path: Domain
      - path: Foundation
      - path: Service
      - path: UI
    dependencies:
      - framework: SDK/google_signin_sdk_4_4_0/GoogleSignIn.bundle
      - framework: SDK/google_signin_sdk_4_4_0/GoogleSignIn.framework
      - framework: SDK/google_signin_sdk_4_4_0/GoogleSignInDependencies.framework
      - carthage: Alamofire
      - carthage: BrightFutures
      - carthage: FacebookCore
      - carthage: FacebookLogin
      - carthage: FBSDKCoreKit
      - carthage: FBSDKLoginKit
      - carthage: FMDB
      - carthage: Hero
      - carthage: KeychainAccess
      - carthage: SDWebImage
      - carthage: Swinject
      - carthage: SwinjectStoryboard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.backit.ios.backer
        SWIFT_OBJC_BRIDGING_HEADER: Backit-Bridging-Header.h
        OTHER_LDFLAGS: "-ObjC"
    configs:
        Debug:
          CODE_SIGN_IDENTITY: "iPhone Developer"
    scheme:
      environmentVariables:
        ENABLE_SIGNPOST: YES
        OS_ACTIVITY_MODE: "disable"
      testTargets:
        - BackitTests
  BackitTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - BackitTests/
    dependencies:
      - target: Backit
      - carthage: KIF
      - carthage: Nimble
      - carthage: Quick
    scheme:
      gatherCoverageData: true
